// Erdkunde (Fokus Schweiz) – 100 Fragen (50 leicht d:false, 50 schwer d:true)
// Richtige Antworten: ~25 je an Position 0, 1, 2, 3
const QUESTIONS_ERDKUNDE = [
    // ---- LEICHT (d: false) ----
    { q: "Was ist die Hauptstadt der Schweiz?", o: ["Zürich", "Genf", "Bern", "Basel"], a: 2, d: false },
    { q: "Wie viele Kantone hat die Schweiz?", o: ["20", "23", "26", "29"], a: 2, d: false },
    { q: "Welches ist der höchste Berg der Schweiz?", o: ["Eiger", "Matterhorn", "Jungfrau", "Dufourspitze"], a: 3, d: false },
    { q: "Wie viele Landessprachen hat die Schweiz?", o: ["2", "3", "4", "5"], a: 2, d: false },
    { q: "Welcher See liegt zwischen der Schweiz und Deutschland?", o: ["Genfersee", "Zürichsee", "Bodensee", "Luganersee"], a: 2, d: false },
    { q: "Welches Land grenzt im Norden an die Schweiz?", o: ["Frankreich", "Italien", "Österreich", "Deutschland"], a: 3, d: false },
    { q: "In welcher Stadt liegt der Hauptsitz des Internationalen Roten Kreuzes?", o: ["Zürich", "Bern", "Genf", "Basel"], a: 2, d: false },
    { q: "Welcher Fluss fliesst durch die Stadt Zürich?", o: ["Aare", "Rhein", "Rhone", "Limmat"], a: 3, d: false },
    { q: "Welche Sprache wird in der Westschweiz hauptsächlich gesprochen?", o: ["Deutsch", "Italienisch", "Rätoromanisch", "Französisch"], a: 3, d: false },
    { q: "Was ist die grösste Stadt der Schweiz nach Einwohnerzahl?", o: ["Bern", "Genf", "Basel", "Zürich"], a: 3, d: false },
    { q: "Welches Land grenzt im Süden an die Schweiz?", o: ["Frankreich", "Österreich", "Italien", "Liechtenstein"], a: 2, d: false },
    { q: "Welcher bekannte Berg hat eine charakteristische Pyramidenform und liegt im Wallis?", o: ["Eiger", "Finsteraarhorn", "Matterhorn", "Weisshorn"], a: 2, d: false },
    { q: "Wie heisst der grösste See der Schweiz?", o: ["Neuenburgersee", "Zürichsee", "Bodensee (CH-Anteil)", "Genfersee"], a: 3, d: false },
    { q: "Welche Stadt gilt als Schweizer Wirtschaftsmetropole und Finanzplatz?", o: ["Bern", "Genf", "Zürich", "Basel"], a: 2, d: false },
    { q: "Welcher Kanton trägt den Löwen im Wappen?", o: ["Bern", "Zürich", "Luzern", "Genf"], a: 0, d: false },
    { q: "Wie heisst die Region im Süden der Schweiz, in der Italienisch gesprochen wird?", o: ["Graubünden", "Wallis", "Tessin", "Jura"], a: 2, d: false },
    { q: "Welcher Pass verbindet die Schweiz mit Italien über das Wallis?", o: ["Gotthard", "Simplon", "Bernina", "Julier"], a: 1, d: false },
    { q: "Was ist die Währung der Schweiz?", o: ["Euro", "Schweizer Franken", "Rappen (allein)", "Krone"], a: 1, d: false },
    { q: "Welches Gebirge prägt die Schweizer Landschaft?", o: ["Pyrenäen", "Karpaten", "Alpen", "Dolomiten"], a: 2, d: false },
    { q: "Welcher Kanton hat das Kantonszeichen ZH?", o: ["Zug", "Zermatt", "Zürich", "Zweisimmen"], a: 2, d: false },
    { q: "An welchen Kanton grenzt die Stadt Basel im Osten (der Kanton heisst)?", o: ["Solothurn", "Aargau", "Basel-Landschaft", "Jura"], a: 2, d: false },
    { q: "Welcher Fluss fliesst durch Bern?", o: ["Rhein", "Reuss", "Aare", "Limmat"], a: 2, d: false },
    { q: "Welches ist das Kürzel des Kantons Genf?", o: ["GE", "GL", "GR", "GS"], a: 0, d: false },
    { q: "Wie viele Nachbarländer hat die Schweiz?", o: ["3", "4", "5", "6"], a: 2, d: false },
    { q: "Welche Stadt ist Sitz des Bundesrats der Schweiz?", o: ["Zürich", "Lausanne", "Bern", "Lugano"], a: 2, d: false },
    { q: "Welcher Kanton liegt vollständig südlich der Alpen?", o: ["Wallis", "Graubünden", "Tessin", "Uri"], a: 2, d: false },
    { q: "Wie heisst die Schweizer Region, die an Frankreich, Deutschland und Österreich grenzt?", o: ["Tessin", "Jura", "Graubünden", "Bodenseeregion (Ostschweiz)"], a: 3, d: false },
    { q: "Welche Sprache sprechen die Menschen im Kanton Graubünden neben Deutsch und Italienisch?", o: ["Französisch", "Englisch", "Rätoromanisch", "Bairisch"], a: 2, d: false },
    { q: "Wie heisst der Fluss, der den Genfersee verlässt?", o: ["Aare", "Rhone", "Rhein", "Saane"], a: 1, d: false },
    { q: "Welcher internationale Flughafen liegt in der Nähe von Zürich?", o: ["EuroAirport Basel", "Flughafen Bern-Belp", "Flughafen Zürich (Kloten)", "Flughafen Lugano"], a: 2, d: false },
    { q: "Welcher Kanton liegt im Herzen der Alpen und grenzt an Uri, Nidwalden, Luzern und Bern?", o: ["Schwyz", "Glarus", "Obwalden", "Zug"], a: 2, d: false },
    { q: "Was ist die Landschaft des Schweizer Mittellandes hauptsächlich geprägt von?", o: ["Wüsten", "Seen, Hügeln und landwirtschaftlichen Flächen", "Hochgebirge", "Tiefebenen ohne Seen"], a: 1, d: false },
    { q: "Welche Stadt liegt am Ufer des Neuenburgersees?", o: ["Neuenburg (Neuchâtel)", "Freiburg", "Solothurn", "Biel"], a: 0, d: false },
    { q: "Wie heisst der längste Tunnel der Welt (Gotthard-Basistunnel)?", o: ["Er ist 35 km lang", "Er ist 57 km lang", "Er ist 45 km lang", "Er ist 67 km lang"], a: 1, d: false },
    { q: "Welches Schweizer Wahrzeichen sind die drei Berge Eiger, Mönch und…?", o: ["Jungfrau", "Schreckhorn", "Fiescherhorn", "Aletschhorn"], a: 0, d: false },
    { q: "Welche Region der Schweiz ist für Uhrenherstellung bekannt?", o: ["Tessin", "Ostschweiz", "Jura und Neuenburger Region", "Zentralschweiz"], a: 2, d: false },
    { q: "Welcher Kanton hat das Kürzel VS?", o: ["Waadt", "Wallis", "Vaud", "Vierwaldstättersee-Kanton"], a: 1, d: false },
    { q: "In welchem Kanton liegt das Skigebiet Zermatt?", o: ["Bern", "Uri", "Graubünden", "Wallis"], a: 3, d: false },
    { q: "Wie heisst der Nationalpark der Schweiz und in welchem Kanton liegt er?", o: ["Nationalpark Schweiz, im Kanton Graubünden", "Nationalpark Jura, im Kanton Jura", "Nationalpark Tessin, im Kanton Tessin", "Nationalpark Aletsch, im Kanton Wallis"], a: 0, d: false },
    { q: "Welcher Kanton hat das grösste Kantonsgebiet?", o: ["Bern", "Wallis", "Graubünden", "Uri"], a: 2, d: false },
    { q: "Welcher See liegt zwischen Lausanne und Genf?", o: ["Thuner See", "Bielersee", "Murtensee", "Genfersee"], a: 3, d: false },
    { q: "Wie heisst die Halbinsel zwischen Zürichsee und Greifensee?", o: ["Küsnachter Halbinsel", "Pfannenstiel", "Zürichberg", "Albiskette"], a: 1, d: false },
    { q: "Welcher grosse europäische Fluss entspringt in der Schweiz und fliesst durch Deutschland?", o: ["Donau", "Elbe", "Rhein", "Main"], a: 2, d: false },
    { q: "In welchem Kanton liegt die Stadt Lausanne?", o: ["Genf", "Freiburg", "Neuenburg", "Waadt"], a: 3, d: false },
    { q: "Welches Gebirge bildet die Grenze zwischen der Deutschen Schweiz und dem Mittelland?", o: ["Alpen", "Jura", "Schwarzwald", "Vogesen"], a: 1, d: false },
    { q: "In welcher Stadt hat der Internationale Gerichtshof für Sportschiedsgerichtsbarkeit (TAS/CAS) seinen Sitz?", o: ["Genf", "Bern", "Zürich", "Lausanne"], a: 3, d: false },
    { q: "Welcher Kanton hat das Kürzel ZG?", o: ["Zürich", "Zermatt", "Zug", "Zweisimmen-Kanton"], a: 2, d: false },
    { q: "Wie nennt man die vier Sprachregionen der Schweiz?", o: ["Deutschschweiz, Romandie, Svizzera italiana, Rumantschia", "Nord, Süd, Ost, West", "Alpen, Mittelland, Jura, Tessin", "Bund, Kanton, Gemeinde, Region"], a: 0, d: false },
    { q: "Welches ist der kleinste Kanton der Schweiz nach Fläche?", o: ["Zug", "Nidwalden", "Basel-Stadt", "Appenzell Innerrhoden"], a: 2, d: false },
    { q: "Welcher Kanton hat das Kürzel BE?", o: ["Basel-Stadt", "Bern", "Basel-Landschaft", "Biel"], a: 1, d: false },

    // ---- SCHWER (d: true) ----
    { q: "Wie viele Einwohner hat die Schweiz (ungefähre Zahl, Stand ca. 2024)?", o: ["7 Millionen", "8,9 Millionen", "10,5 Millionen", "6,5 Millionen"], a: 1, d: true },
    { q: "Wie hoch ist die Dufourspitze (höchster Berg der Schweiz)?", o: ["4 478 m", "4 634 m", "4 165 m", "4 810 m"], a: 1, d: true },
    { q: "Welcher Kanton hat die meisten Einwohner?", o: ["Bern", "Waadt", "Aargau", "Zürich"], a: 3, d: true },
    { q: "In welchem Jahr trat die Schweiz den Vereinten Nationen bei?", o: ["1991", "1995", "2002", "2008"], a: 2, d: true },
    { q: "Wie lang ist der Gotthard-Basistunnel (eröffnet 2016)?", o: ["45,5 km", "50,0 km", "57,1 km", "63,0 km"], a: 2, d: true },
    { q: "Wie viele Halbkantone gibt es in der Schweiz?", o: ["4", "6", "8", "10"], a: 1, d: true },
    { q: "Wie heisst der höchste Alpenpass der Schweiz, der mit dem Auto befahren werden kann?", o: ["Gotthard", "Bernina", "Umbrail", "Julier"], a: 2, d: true },
    { q: "Welcher Kanton hat das kleinste Kantonsgebiet nach Fläche?", o: ["Zug", "Basel-Stadt", "Appenzell Innerrhoden", "Nidwalden"], a: 1, d: true },
    { q: "Wie heisst das Schweizer Mittelland auf Französisch?", o: ["Plateau Suisse", "La Plaine", "Le Plateau", "Suisse centrale"], a: 0, d: true },
    { q: "Welcher Schweizer Kanton grenzt an Frankreich, Italien und Deutschland?", o: ["Wallis", "Graubünden", "Kein einzelner Kanton grenzt an alle drei", "Tessin"], a: 2, d: true },
    { q: "In welchem Kanton liegt die Stadt Chur?", o: ["Uri", "Glarus", "Graubünden", "St. Gallen"], a: 2, d: true },
    { q: "Was ist das BIP der Schweiz pro Kopf (ungefähr, Stand ca. 2023)?", o: ["40 000 USD", "60 000 USD", "85 000 USD", "100 000 USD"], a: 2, d: true },
    { q: "Wie heisst der grösste Gletscher der Alpen?", o: ["Gornergletscher", "Aletschgletscher", "Morteratschgletscher", "Rhonegletscher"], a: 1, d: true },
    { q: "Welcher Kanton hat das Kürzel OW?", o: ["Ostwald", "Obwalden", "Oberes Wallis", "Ost-Waadt"], a: 1, d: true },
    { q: "Wie viele Kantone grenzen an den Kanton Bern?", o: ["5", "6", "7", "8"], a: 2, d: true },
    { q: "Welche zwei Kantone bilden zusammen den ehemaligen Kanton Unterwalden?", o: ["Uri und Schwyz", "Nidwalden und Obwalden", "Zug und Schwyz", "Glarus und Uri"], a: 1, d: true },
    { q: "Welcher Schweizer See ist der drittgrösste in der Schweiz?", o: ["Zürichsee", "Bodensee (CH-Anteil)", "Neuenburgersee", "Vierwaldstättersee"], a: 3, d: true },
    { q: "Wie heisst der Pass, der den Kanton Uri mit dem Kanton Tessin verbindet?", o: ["Simplon", "San Bernardino", "Gotthard", "Susten"], a: 2, d: true },
    { q: "Welches ist der bevölkerungsreichste Kanton der Romandie?", o: ["Genf", "Neuenburg", "Freiburg", "Waadt"], a: 3, d: true },
    { q: "Wie heisst der Kanton, der vollständig vom Kanton Bern umgeben ist?", o: ["Zug", "Schwyz", "Nidwalden", "Es gibt keinen solchen Kanton"], a: 3, d: true },
    { q: "Welche Schweizer Stadt ist Sitz des Europäischen Gerichtshofs für Menschenrechte?", o: ["Genf", "Bern", "Strassburg (Frankreich, nicht Schweiz)", "Zürich"], a: 2, d: true },
    { q: "Wie heisst der längste Fluss, der vollständig in der Schweiz liegt?", o: ["Rhein", "Rhone", "Aare", "Reuss"], a: 2, d: true },
    { q: "Welcher Pass verbindet das Engadin mit dem Veltlin in Italien?", o: ["Malojapass", "Berninapass", "Julierpas", "Ofenpass"], a: 0, d: true },
    { q: "In welchem Kanton liegt der Ort Appenzell?", o: ["Appenzell Ausserrhoden", "Appenzell Innerrhoden", "St. Gallen", "Thurgau"], a: 1, d: true },
    { q: "Wie heisst das UNESCO-Weltnaturerbe-Gebiet mit dem Aletschgletscher?", o: ["Schweizer Alpen Jungfrau-Aletsch", "Alpenpark Tessin", "Drei-Seen-Land", "Engadiner Nationalpark"], a: 0, d: true },
    { q: "Welches ist die höchste Bahnstation Europas (regulär mit Personenzügen)?", o: ["Kleine Scheidegg", "Gornergrat", "Jungfraujoch (3 454 m)", "Pilatus (2 073 m)"], a: 2, d: true },
    { q: "Wie heisst der südlichste Kanton der Schweiz?", o: ["Genf", "Wallis", "Graubünden", "Tessin"], a: 3, d: true },
    { q: "Wie viele Kantone grenzen an den Kanton Zürich?", o: ["5", "6", "7", "8"], a: 1, d: true },
    { q: "Welcher Schweizer Kanton hat die höchste durchschnittliche Meereshöhe?", o: ["Uri", "Wallis", "Graubünden", "Glarus"], a: 2, d: true },
    { q: "Wie heisst der grösste Naturpark der Schweiz?", o: ["Nationalpark Graubünden", "Naturpark Jura", "Naturpark Beverin", "Naturpark Diemtigtal"], a: 0, d: true },
    { q: "Welcher Fluss entspringt am Gotthard und fliesst in den Rhein?", o: ["Reuss", "Ticino", "Aare", "Inn"], a: 0, d: true },
    { q: "Wie viele Einwohner hat die Stadt Zürich ungefähr (Stand ca. 2024)?", o: ["250 000", "340 000", "430 000", "520 000"], a: 2, d: true },
    { q: "Welcher Kanton hat das Kürzel FR?", o: ["Fricktal", "Freiburg", "Frenkenthal", "Fraubrunnen"], a: 1, d: true },
    { q: "Welcher See liegt zwischen der Schweiz und Österreich und wird auch als Teil des Bodensees betrachtet?", o: ["Untersee", "Überlinger See", "Zeller See", "Rheinsee"], a: 0, d: true },
    { q: "Welche Stadt ist Hauptort des Kantons Solothurn?", o: ["Olten", "Grenchen", "Solothurn", "Biberist"], a: 2, d: true },
    { q: "Wie heisst der höchste Punkt des Juras?", o: ["Mont Soleil", "Chasseral", "Mont Tendre", "Weissenstein"], a: 2, d: true },
    { q: "Welcher Kanton liegt ganz im Norden der Schweiz, grenzt an Deutschland und hat ein markantes Band im Wappen?", o: ["Schaffhausen", "Thurgau", "Basel-Landschaft", "Aargau"], a: 0, d: true },
    { q: "Wie heisst die grösste Messe der Schweiz für Uhren und Schmuck?", o: ["Baselworld / Watches and Wonders", "Zurich Watch Fair", "Geneva Jewel Show", "Swiss Expo"], a: 0, d: true },
    { q: "Welcher Kanton hat den längsten Küstenabschnitt am Genfersee?", o: ["Genf", "Freiburg", "Waadt", "Wallis"], a: 2, d: true },
    { q: "Wie heisst der Zusammenfluss von Aare und Rhein?", o: ["Koblenz AG", "Waldshut", "Rheinfelden", "Aarau"], a: 0, d: true },
    { q: "Welcher Schweizer Berg ist mit 4 634 m der zweithöchste?", o: ["Liskamm", "Weisshorn", "Matterhorn", "Dom"], a: 3, d: true },
    { q: "Wie gross ist die Fläche der Schweiz in km²?", o: ["30 000 km²", "37 285 km²", "41 285 km²", "45 000 km²"], a: 2, d: true },
    { q: "Welche Stadt ist Hauptort des Kantons Graubünden?", o: ["Davos", "Chur", "St. Moritz", "Arosa"], a: 1, d: true },
    { q: "In welchem Kanton liegt Locarno?", o: ["Graubünden", "Tessin", "Wallis", "Uri"], a: 1, d: true },
    { q: "Welcher Kanton hat das Kürzel SH?", o: ["Schwyz", "St. Gallen", "Solothurn", "Schaffhausen"], a: 3, d: true },
    { q: "Welche Schweizer Region ist für den Weinanbau am bekanntesten?", o: ["Graubünden (Bündner Herrschaft) und Waadt", "Zürich und Thurgau", "Uri und Schwyz", "Tessin (nur Grappa)"], a: 0, d: true },
    { q: "Wie heisst der wichtigste Wirtschaftszweig der Schweiz in Bezug auf Exportwert (Stand ca. 2023)?", o: ["Tourismus", "Landwirtschaft", "Pharmaindustrie und chemische Industrie", "Uhrenindustrie"], a: 2, d: true },
    { q: "Welcher Kanton wurde 1979 als letzter Kanton in die Eidgenossenschaft aufgenommen?", o: ["Appenzell Innerrhoden", "Nidwalden", "Jura", "Luzern"], a: 2, d: true },
    { q: "Wie heisst der Hauptort des Kantons Appenzell Innerrhoden?", o: ["Herisau", "Appenzell", "Trogen", "Hundwil"], a: 1, d: true },
    { q: "Welcher Rheinzufluss bildet die Grenze zwischen der Schweiz und Liechtenstein?", o: ["Ill", "Alpenrhein", "Hinterrhein", "Vorderrhein"], a: 1, d: true },
];
