// Physik – 100 Fragen (50 leicht d:false, 50 schwer d:true)
// Richtige Antworten: ~25 je an Position 0, 1, 2, 3
const QUESTIONS_PHYSIK = [
    // ---- LEICHT (d: false) ----
    { q: "Was ist die SI-Einheit der Kraft?", o: ["Joule", "Newton", "Watt", "Pascal"], a: 1, d: false },
    { q: "Was misst ein Thermometer?", o: ["Luftdruck", "Luftfeuchtigkeit", "Temperatur", "Windgeschwindigkeit"], a: 2, d: false },
    { q: "Mit welcher Einheit wird elektrische Spannung gemessen?", o: ["Ampere", "Ohm", "Volt", "Watt"], a: 2, d: false },
    { q: "Was ist Licht?", o: ["Eine Schallwelle", "Eine mechanische Welle", "Eine elektromagnetische Welle", "Eine Wasserwelle"], a: 2, d: false },
    { q: "Welche Farbe hat sichtbares Licht mit der kürzesten Wellenlänge?", o: ["Rot", "Grün", "Gelb", "Violett"], a: 3, d: false },
    { q: "Was versteht man unter Aggregatzustand?", o: ["Die Farbe eines Stoffes", "Die Masse eines Stoffes", "Den Zustand eines Stoffes (fest, flüssig, gasförmig)", "Den Geruch eines Stoffes"], a: 2, d: false },
    { q: "Welche Einheit hat die elektrische Stromstärke?", o: ["Volt", "Watt", "Ohm", "Ampere"], a: 3, d: false },
    { q: "Was beschreibt das Ohmsche Gesetz?", o: ["Den Zusammenhang von Masse und Beschleunigung", "Den Zusammenhang von Spannung, Strom und Widerstand", "Die Lichtgeschwindigkeit im Vakuum", "Den Energieerhaltungssatz"], a: 1, d: false },
    { q: "Wie schnell bewegt sich Schall in Luft ungefähr?", o: ["3 000 m/s", "340 m/s", "1 500 m/s", "100 m/s"], a: 1, d: false },
    { q: "Was ist die Einheit der Energie?", o: ["Newton", "Watt", "Joule", "Pascal"], a: 2, d: false },
    { q: "Welcher Aggregatzustand hat keine feste Form und kein festes Volumen?", o: ["Fest", "Flüssig", "Gasförmig", "Plasma"], a: 2, d: false },
    { q: "Was ist die Erdanziehungskraft auf einen Körper?", o: ["Masse", "Gewichtskraft", "Dichte", "Druck"], a: 1, d: false },
    { q: "Was gibt die Dichte an?", o: ["Masse pro Volumen", "Kraft pro Fläche", "Energie pro Zeit", "Weg pro Zeit"], a: 0, d: false },
    { q: "Welche Einheit hat die Frequenz?", o: ["Meter", "Sekunde", "Hertz", "Watt"], a: 2, d: false },
    { q: "Was ist ein Isolator?", o: ["Ein Stoff, der Strom gut leitet", "Ein Stoff, der Strom schlecht leitet", "Ein Stoff, der magnetisch ist", "Ein Stoff, der Wärme erzeugt"], a: 1, d: false },
    { q: "Was versteht man unter Reflexion?", o: ["Brechung von Licht", "Absorption von Licht", "Zurückwerfen von Licht oder Schall", "Streuung von Licht"], a: 2, d: false },
    { q: "Was misst ein Barometer?", o: ["Temperatur", "Luftfeuchtigkeit", "Luftdruck", "Windstärke"], a: 2, d: false },
    { q: "Welche Farbe hat sichtbares Licht mit der längsten Wellenlänge?", o: ["Rot", "Blau", "Grün", "Violett"], a: 0, d: false },
    { q: "Was ist die Einheit der Leistung?", o: ["Joule", "Newton", "Ampere", "Watt"], a: 3, d: false },
    { q: "Welcher Physiker formulierte die allgemeine Relativitätstheorie?", o: ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Max Planck"], a: 2, d: false },
    { q: "Was beschreibt Newtons erstes Gesetz (Trägheitsprinzip)?", o: ["Kraft = Masse × Beschleunigung", "Jeder Körper verharrt in Ruhe oder gleichförmiger Bewegung, solange keine Kraft wirkt", "Zu jeder Wirkung gibt es eine gleich grosse Gegenwirkung", "Energie bleibt erhalten"], a: 1, d: false },
    { q: "Welche Einheit hat der Druck?", o: ["Newton", "Joule", "Watt", "Pascal"], a: 3, d: false },
    { q: "Was ist ein Magnet?", o: ["Ein Körper, der elektrischen Strom leitet", "Ein Körper, der andere Metalle anzieht oder abstösst", "Ein Körper, der Licht bricht", "Ein Körper, der Wärme speichert"], a: 1, d: false },
    { q: "Was ist die Geschwindigkeit des Lichts im Vakuum (gerundet)?", o: ["300 000 km/s", "150 000 km/s", "3 000 km/s", "30 000 km/s"], a: 0, d: false },
    { q: "Was ist ein Atom?", o: ["Die kleinste Einheit eines chemischen Elements", "Ein Molekül aus zwei Wasserstoffatomen", "Eine Einheit elektrischer Ladung", "Eine Masseneinheit"], a: 0, d: false },
    { q: "Was versteht man unter Brechung?", o: ["Das Zurückwerfen von Licht", "Die Ablenkung von Licht beim Übergang zwischen zwei Medien", "Die Absorption von Licht", "Das Streuen von Licht"], a: 1, d: false },
    { q: "Welche Einheit wird für den elektrischen Widerstand verwendet?", o: ["Volt", "Ampere", "Ohm", "Watt"], a: 2, d: false },
    { q: "Was versteht man unter kinetischer Energie?", o: ["Energie eines ruhenden Körpers aufgrund seiner Höhe", "Energie eines Körpers aufgrund seiner Bewegung", "Energie gespeichert in chemischen Bindungen", "Wärmeenergie eines Körpers"], a: 1, d: false },
    { q: "Was ist Schwerkraft?", o: ["Die Kraft zwischen zwei Ladungen", "Die Anziehungskraft zwischen Massen", "Die Kraft zwischen Magneten", "Die Kraft, die Elektronen bindet"], a: 1, d: false },
    { q: "Was misst ein Voltmeter?", o: ["Stromstärke", "Widerstand", "Leistung", "Spannung"], a: 3, d: false },
    { q: "Wie nennt man den Übergang von fest zu flüssig?", o: ["Verdampfen", "Kondensieren", "Schmelzen", "Erstarren"], a: 2, d: false },
    { q: "Was ist Schall?", o: ["Eine elektromagnetische Welle", "Eine mechanische Druckwelle", "Ein Lichtstrahl", "Ein elektrisches Feld"], a: 1, d: false },
    { q: "Welche Kraft wirkt auf einen Körper im Wasser nach oben?", o: ["Schwerkraft", "Reibungskraft", "Auftriebskraft", "Magnetkraft"], a: 2, d: false },
    { q: "Was ist Potenzielle Energie?", o: ["Energie durch Bewegung", "Energie durch elektrische Ladung", "Energie durch Lage im Schwerefeld", "Energie durch chemische Reaktion"], a: 2, d: false },
    { q: "Mit welchem Gerät misst man die Stromstärke?", o: ["Voltmeter", "Ohmmeter", "Amperemeter", "Wattmeter"], a: 2, d: false },
    { q: "Was bedeutet Energie erhalten?", o: ["Energie kann erzeugt werden", "Energie kann vernichtet werden", "Energie bleibt in einem geschlossenen System konstant", "Energie nimmt immer zu"], a: 2, d: false },
    { q: "Welche Einheit hat die Masse?", o: ["Newton", "Kilogramm", "Pascal", "Joule"], a: 1, d: false },
    { q: "Was ist Reibung?", o: ["Eine Kraft, die Körper beschleunigt", "Eine Kraft, die der Bewegung entgegenwirkt", "Eine elektrische Kraft", "Eine magnetische Kraft"], a: 1, d: false },
    { q: "Was passiert, wenn sich zwei gleiche Magnetpole berühren?", o: ["Sie ziehen sich an", "Sie stossen sich ab", "Nichts passiert", "Sie verschmelzen"], a: 1, d: false },
    { q: "Was ist ein Leiter in der Elektrizitätslehre?", o: ["Ein Stoff mit hohem Widerstand", "Ein Stoff, der Strom gut leitet", "Ein Stoff, der Licht bricht", "Ein Stoff, der magnetisch ist"], a: 1, d: false },
    { q: "Welche Strahlung hat die höchste Energie?", o: ["Radiowellen", "Infrarotstrahlung", "Sichtbares Licht", "Gammastrahlung"], a: 3, d: false },
    { q: "Was gibt die Wellenlänge an?", o: ["Die Höhe einer Welle", "Den Abstand zwischen zwei Wellenbergen", "Die Geschwindigkeit einer Welle", "Die Energie einer Welle"], a: 1, d: false },
    { q: "Wie nennt man den Übergang von flüssig zu gasförmig?", o: ["Schmelzen", "Kondensieren", "Erstarren", "Verdampfen"], a: 3, d: false },
    { q: "Was ist ein Proton?", o: ["Ein negativ geladenes Teilchen im Atomkern", "Ein positiv geladenes Teilchen im Atomkern", "Ein neutrales Teilchen im Atomkern", "Ein Teilchen in der Atomhülle"], a: 1, d: false },
    { q: "Was ist ein Neutron?", o: ["Ein positiv geladenes Teilchen", "Ein negativ geladenes Teilchen", "Ein neutrales Teilchen im Atomkern", "Ein Teilchen in der Atomhülle"], a: 2, d: false },
    { q: "Was ist ein Elektron?", o: ["Ein positiv geladenes Teilchen im Kern", "Ein neutrales Teilchen im Kern", "Ein negativ geladenes Teilchen in der Atomhülle", "Ein Teilchen ohne Masse"], a: 2, d: false },
    { q: "Was versteht man unter Wärmeleitung?", o: ["Wärmetransport durch Strahlung", "Wärmetransport durch Strömung", "Wärmetransport durch direkten Kontakt", "Wärmetransport durch Konvektion"], a: 2, d: false },
    { q: "Was ist ein Hebel?", o: ["Ein elektrisches Bauteil", "Ein einfaches Werkzeug, das Kräfte über einen Drehpunkt überträgt", "Ein Messgerät für Druck", "Ein Wellentyp"], a: 1, d: false },
    { q: "Was versteht man unter Konvektion?", o: ["Wärmetransport durch direkten Kontakt", "Wärmetransport durch Strahlung", "Wärmetransport durch Strömung von Flüssigkeiten oder Gasen", "Wärmetransport durch Leitung"], a: 2, d: false },
    { q: "Welche Einheit hat die Geschwindigkeit?", o: ["Meter", "Sekunde", "Meter pro Sekunde", "Kilogramm"], a: 2, d: false },

    // ---- SCHWER (d: true) ----
    { q: "Welche Formel beschreibt Newtons zweites Gesetz?", o: ["E = mc²", "F = m × a", "P = U × I", "W = F × s"], a: 1, d: true },
    { q: "Welchen Wert hat die Gravitationskonstante G ungefähr?", o: ["9,81 m/s²", "6,674 × 10⁻¹¹ N·m²/kg²", "3 × 10⁸ m/s", "1,6 × 10⁻¹⁹ C"], a: 1, d: true },
    { q: "Was besagt Einsteins berühmte Formel E = mc²?", o: ["Energie ist gleich Masse mal Lichtgeschwindigkeit", "Energie ist gleich Masse mal dem Quadrat der Lichtgeschwindigkeit", "Energie ist gleich Masse durch Lichtgeschwindigkeit", "Energie ist proportional zur Frequenz"], a: 1, d: true },
    { q: "Was beschreibt das Plancksche Wirkungsquantum h?", o: ["Die Mindestenergie eines Photons bei gegebener Frequenz", "Die Lichtgeschwindigkeit im Vakuum", "Die Gravitationskonstante", "Den Zusammenhang von Strom und Spannung"], a: 0, d: true },
    { q: "Wie lautet die Formel für elektrische Leistung?", o: ["P = F × v", "P = m × a", "P = U × I", "P = W / m"], a: 2, d: true },
    { q: "Was ist der erste Hauptsatz der Thermodynamik?", o: ["Wärme fliesst immer von kalt nach warm", "Die innere Energie eines Systems ändert sich um Wärme plus Arbeit", "Entropie nimmt immer zu", "Im Gleichgewicht sind alle Temperaturen gleich"], a: 1, d: true },
    { q: "Was beschreibt der zweite Hauptsatz der Thermodynamik?", o: ["Energieerhaltung", "Wärme fliesst spontan von warm nach kalt; Entropie nimmt zu", "Die Beziehung zwischen Druck und Volumen", "Den elektrischen Widerstand"], a: 1, d: true },
    { q: "Wie lautet das Ohmsche Gesetz?", o: ["U = R / I", "I = U / R", "R = U × I", "U = I² × R"], a: 1, d: true },
    { q: "Welche Formel berechnet kinetische Energie?", o: ["E_kin = m × g × h", "E_kin = ½ × m × v²", "E_kin = F × s", "E_kin = P × t"], a: 1, d: true },
    { q: "Was ist die Einheit des magnetischen Flusses?", o: ["Tesla", "Ampere", "Weber", "Henry"], a: 2, d: true },
    { q: "Welches Gesetz beschreibt die Induktionsspannung in einer Spule?", o: ["Ohmsches Gesetz", "Faradaysches Induktionsgesetz", "Coulombsches Gesetz", "Kirchhoffsches Gesetz"], a: 1, d: true },
    { q: "Wie lautet die Formel für Coulombkraft?", o: ["F = G × m₁ × m₂ / r²", "F = q × E", "F = k × q₁ × q₂ / r²", "F = m × a"], a: 2, d: true },
    { q: "Was besagt das Gesetz von Boyle-Mariotte?", o: ["Volumen ist proportional zur Temperatur bei konstantem Druck", "Druck × Volumen = konstant bei konstanter Temperatur", "Druck ist proportional zur Temperatur bei konstantem Volumen", "Alle Gase verhalten sich ideal"], a: 1, d: true },
    { q: "Welchen Wert hat die Elementarladung e?", o: ["1,6 × 10⁻¹⁹ C", "9,11 × 10⁻³¹ kg", "6,674 × 10⁻¹¹ N·m²/kg²", "1,38 × 10⁻²³ J/K"], a: 0, d: true },
    { q: "Was ist der Unterschied zwischen Kern- und Halbwertszeit?", o: ["Es gibt keinen Unterschied", "Kernzeit ist doppelt so lang", "Halbwertszeit ist die Zeit, bis die Hälfte der radioaktiven Kerne zerfallen ist", "Kernzeit beschreibt stabile Kerne"], a: 2, d: true },
    { q: "Welche Formel beschreibt die Gravitationskraft zwischen zwei Massen?", o: ["F = m × g", "F = G × m₁ × m₂ / r²", "F = k × q₁ × q₂ / r²", "F = m × a"], a: 1, d: true },
    { q: "Was ist die De-Broglie-Wellenlänge?", o: ["Die Wellenlänge von Röntgenstrahlen", "Die Wellenlänge, die einem bewegten Teilchen zugeordnet wird", "Die Wellenlänge sichtbaren Lichts", "Die Wellenlänge von Gammastrahlung"], a: 1, d: true },
    { q: "Was beschreibt die Heisenbergsche Unschärferelation?", o: ["Ort und Impuls eines Teilchens können nicht gleichzeitig beliebig genau gemessen werden", "Energie und Masse sind äquivalent", "Der Welle-Teilchen-Dualismus", "Die Lichtgeschwindigkeit ist konstant"], a: 0, d: true },
    { q: "Was ist Quantenmechanik?", o: ["Die Physik sehr schneller Körper", "Die Physik sehr grosser Massen", "Die Physik auf atomarer und subatomarer Ebene", "Die Physik sehr tiefer Temperaturen"], a: 2, d: true },
    { q: "Wie lautet die Formel für den Brechungsindex?", o: ["n = c / v", "n = v / c", "n = λ × f", "n = E / h"], a: 0, d: true },
    { q: "Was ist ein Schwarzes Loch?", o: ["Ein Stern mit sehr geringer Masse", "Ein Objekt mit so starker Gravitation, dass selbst Licht es nicht verlassen kann", "Eine Lücke im Universum", "Ein ausgebrannter Planet"], a: 1, d: true },
    { q: "Was beschreibt Kirchhoffs Knotenregel?", o: ["Die Summe aller Spannungen im Kreis ist null", "Die Summe der zufliessenden Ströme an einem Knoten gleicht der Summe der abfliessenden", "Der Widerstand ist proportional zur Länge", "Spannung ist gleich Strom mal Widerstand"], a: 1, d: true },
    { q: "Wie gross ist die Ruhemasse eines Elektrons?", o: ["1,67 × 10⁻²⁷ kg", "9,11 × 10⁻³¹ kg", "1,6 × 10⁻¹⁹ kg", "6,02 × 10²³ kg"], a: 1, d: true },
    { q: "Was ist Radioaktivität?", o: ["Das Leuchten bestimmter Stoffe", "Der spontane Zerfall instabiler Atomkerne unter Aussendung von Strahlung", "Die Reflexion von Röntgenstrahlen", "Die Leitfähigkeit von Metallen"], a: 1, d: true },
    { q: "Welche drei Arten von radioaktiver Strahlung gibt es?", o: ["Röntgen-, Infrarot- und Ultraviolettstrahlung", "Alpha-, Beta- und Gammastrahlung", "Radio-, Mikrowellen- und Lichtstrahlung", "Teilchen-, Plasma- und Neutronenstrahlung"], a: 1, d: true },
    { q: "Was ist Supraleitung?", o: ["Leitfähigkeit bei sehr hohen Temperaturen", "Leitfähigkeit bei sehr hohem Druck", "Verschwinden des elektrischen Widerstands bei sehr tiefen Temperaturen", "Leitfähigkeit nur für Gleichstrom"], a: 2, d: true },
    { q: "Welche Formel berechnet potenzielle Energie im Schwerefeld?", o: ["E_pot = ½ × m × v²", "E_pot = F × s", "E_pot = P × t", "E_pot = m × g × h"], a: 3, d: true },
    { q: "Was ist ein Quark?", o: ["Ein Elementarteilchen, das Protonen und Neutronen aufbaut", "Ein Typ von Elektron", "Ein Photon mit hoher Energie", "Ein Neutrino"], a: 0, d: true },
    { q: "Was beschreibt das Huygenssche Prinzip?", o: ["Jeder Punkt einer Wellenfront ist Ausgangspunkt einer neuen Kugelwelle", "Licht besteht aus Photonen", "Energie ist gequantelt", "Entropie nimmt zu"], a: 0, d: true },
    { q: "Welchen Wert hat die Boltzmann-Konstante k_B?", o: ["6,674 × 10⁻¹¹ J/K", "1,38 × 10⁻²³ J/K", "1,6 × 10⁻¹⁹ J/K", "6,02 × 10²³ J/K"], a: 1, d: true },
    { q: "Was ist der photoelektrische Effekt?", o: ["Die Aussendung von Licht durch angeregte Elektronen", "Das Herausschlagen von Elektronen aus einem Metall durch Licht", "Die Brechung von Licht in einem Prisma", "Die Absorption von Gammastrahlung"], a: 1, d: true },
    { q: "Was versteht man unter dem Dopplereffekt?", o: ["Die Brechung von Licht", "Die Änderung der wahrgenommenen Frequenz durch Relativbewegung von Quelle und Beobachter", "Die Interferenz zweier Wellen", "Die Reflexion von Schall"], a: 1, d: true },
    { q: "Was ist thermische Strahlung?", o: ["Strahlung durch elektrische Entladung", "Elektromagnetische Strahlung, die ein Körper aufgrund seiner Temperatur aussendet", "Strahlung durch radioaktiven Zerfall", "Strahlung durch chemische Reaktion"], a: 1, d: true },
    { q: "Wie lautet das Gesetz von Gay-Lussac?", o: ["p × V = konstant", "V / T = konstant bei konstantem Druck", "p / T = konstant bei konstantem Volumen", "p × V / T = konstant"], a: 2, d: true },
    { q: "Was ist ein Photon?", o: ["Ein geladenes Lichtteilchen", "Ein masseloses Elementarteilchen des Lichts (elektromagnetische Strahlung)", "Ein Neutron im Atomkern", "Ein Elektron in der Atomhülle"], a: 1, d: true },
    { q: "Was beschreibt Maxwells Gleichungen?", o: ["Die Quantenmechanik", "Die Mechanik fester Körper", "Die grundlegenden Gesetze des elektromagnetischen Feldes", "Die Thermodynamik idealer Gase"], a: 2, d: true },
    { q: "Was ist Kernfusion?", o: ["Die Spaltung schwerer Atomkerne", "Das Verschmelzen leichter Atomkerne zu einem schwereren Kern unter Energiefreisetzung", "Der radioaktive Zerfall eines Kerns", "Die Aufnahme von Neutronen durch einen Kern"], a: 1, d: true },
    { q: "Was ist Kernspaltung?", o: ["Das Verschmelzen zweier Kerne", "Die Spaltung eines schweren Atomkerns in zwei leichtere Kerne unter Energiefreisetzung", "Der Zerfall eines Elektrons", "Die Emission eines Photons durch einen Kern"], a: 1, d: true },
    { q: "Welche Formel beschreibt den relativistischen Energiezuwachs?", o: ["E = ½mv²", "E = mc²", "E = hf", "E = qU"], a: 1, d: true },
    { q: "Was ist ein Fermion?", o: ["Ein Teilchen mit ganzzahligem Spin, das die Bose-Einstein-Statistik befolgt", "Ein Teilchen mit halbzahligem Spin, das dem Pauli-Prinzip gehorcht", "Ein masseloses Teilchen", "Ein zusammengesetztes Teilchen"], a: 1, d: true },
    { q: "Was beschreibt das Pauli-Ausschliessungsprinzip?", o: ["Zwei Photonen können nie den gleichen Zustand haben", "Zwei Fermionen können nie den gleichen Quantenzustand haben", "Energie ist immer erhalten", "Entropie nimmt immer zu"], a: 1, d: true },
    { q: "Was ist die Avogadro-Konstante?", o: ["6,02 × 10²³ Teilchen pro Mol", "1,38 × 10⁻²³ J/K", "8,31 J/(mol·K)", "1,6 × 10⁻¹⁹ C"], a: 0, d: true },
    { q: "Wie lautet die Lorentz-Transformation für die Zeit?", o: ["t' = t × γ, wobei γ = 1/√(1-v²/c²)", "t' = t / γ", "t' = t + v/c", "t' = t - v/c"], a: 0, d: true },
    { q: "Was ist ein Boson?", o: ["Ein Teilchen mit halbzahligem Spin", "Ein Teilchen mit ganzzahligem Spin, das die Bose-Einstein-Statistik befolgt", "Ein Teilchen ohne Spin", "Ein Fermion mit Masse"], a: 1, d: true },
    { q: "Welche Formel gibt die Wellenlänge eines Photons in Abhängigkeit seiner Energie an?", o: ["λ = h × f", "λ = h × c / E", "λ = E / (h × c)", "λ = c / E"], a: 1, d: true },
    { q: "Was ist Interferenz?", o: ["Das Beugen von Wellen an Hindernissen", "Das Überlagern von Wellen, wobei Amplitude zu- oder abnimmt", "Das Zurückwerfen von Wellen", "Das Brechen von Wellen"], a: 1, d: true },
    { q: "Was ist Beugung in der Physik?", o: ["Das Brechen von Licht an Grenzflächen", "Das Ablenken von Wellen an Hindernissen oder Spalten", "Das Zurückwerfen von Schall", "Die Absorption von Licht"], a: 1, d: true },
    { q: "Was beschreibt die spezielle Relativitätstheorie?", o: ["Die Gravitation grosser Massen", "Die Physik von Körpern, die sich mit Lichtgeschwindigkeit oder nahezu bewegen", "Die Quantenmechanik", "Die Thermodynamik"], a: 1, d: true },
    { q: "Was ist ein Plasma?", o: ["Ein sehr heisses Gas mit frei beweglichen Ionen und Elektronen", "Flüssigkeit unter hohem Druck", "Fester Stoff bei sehr tiefer Temperatur", "Ein Gas bei Normaldruck"], a: 0, d: true },
    { q: "Welchen Wert hat die universelle Gaskonstante R?", o: ["8,31 J/(mol·K)", "1,38 × 10⁻²³ J/K", "6,02 × 10²³ mol⁻¹", "9,81 m/s²"], a: 0, d: true },
    { q: "Was ist der Wirkungsgrad einer Maschine?", o: ["Verhältnis von abgegebener Nutzleistung zu zugeführter Leistung", "Verhältnis von Masse zu Volumen", "Verhältnis von Kraft zu Fläche", "Verhältnis von Spannung zu Strom"], a: 0, d: true },
];
